import turtle
def draw_square():
    window=turtle.Screen()
    window.bgcolor("red")
    brad=turtle.Turtle()
    turtle.shapesize(1,1,1)
    turtle.tilt(45)
    brad.shape("arrow")
    brad.color("green")
    brad.speed(6)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)
    brad.forward(100)
    brad.right(90)
    window.exitonclick()
draw_square()

